export const menulist=[
    {
        key:"/home",
        title:"首页"
    },
    {
        key:"/category",
        title:"品类管理"
    },
    {
        key:"/product",
        title:"商品管理"
    },
    {
        key:"/user",
        title:"用户管理"
    },
    {
        key:"/role",
        title:"角色管理"
    },
    {
        key:"/charts/bar",
        title:"柱形图"
    },
    {
        key:"/charts/line",
        title:"折线图"
    },
    {
        key:"/charts/pie",
        title:"饼图"
    },
]